### ISSUE TITLE
sdc3_MAT.c returning empty array in Matlab

### ISSUE THREAD

**Issue by lukasbrnst** [ISMRM/mri_unbound#1]
Hi!

I have problems running sdc3_MAT.c and hope somebody can help me.
First the compilation is successful, but as I try to run sdc3_MAT.c in the testmex.m from this repository using Matlab (2018a) using the MinGW-w64 C/C++ Compiler (18.1.0) which is recommended by Matlab I get a zero array ([]) as return.
I'd be thankful for any hint!

Lukas

**Comment by lukasbrnst** [comment]
I just  solved it.
In case anybody else is running in this problem:
If having installed the MinGW version 18.1.0 (maybe also other versions) the compiler uses 
"-largeArrayDims" as default to use 64bit.
This code however uses 32bit. The following statement makes it 32bit compatible:
mex -compatibleArrayDims sdc3_MAT.c

Lukas

**Comment by curtcorum** [comment]
@lukasbrnst
The "-compatibleArrayDims" option also seems to fix grid3 compilation. Thanks!
